### PR TITLE
Linear search using python in few lines

### PR DESCRIPTION
**Pull request by meetanubhav**
**Linear search using python in few lines, less than the previous commit**
#73

### CODE REVIEW

**Comment by meetanubhav** [comment]
Linear search using python in few lines . #73

I did it in just few lines. Better from previous commit.

**Comment by ayan-b** [comment]
Please add your own code, do not edit others. :)

**Comment by meetanubhav** [comment]
I added my own code with a pull request

**Comment by ayan-b** [comment]
Sorry, but I am unable to understand. Please post the link of your PR which was merged.
Also please read [CONTRIBUTING.md](https://github.com/ayan-b/Linear-Search/blob/master/CONTRIBUTING.md) if you haven't already.

**Pull request closed without merging**
