### PR TITLE
Added Python3 linear search

### PR DESCRIPTION
**Pull request by vinayak42**

### CODE REVIEW

**Comment by ayan-b** [comment]
Consider adding your name to the Contributors section.

**Comment by ayan-b** [comment]
Please add your institution name and/or country name and the language you have added (i.e., python3). Let me know if you have any problem. This helps to make a report end of the year.

**Comment by vinayak42** [comment]
One quick question (since I am new to open source)
If I have forked your repo and made changes to it, and then your repo gets updated (in this case, the 13th contributor is someone else, while in my repo, I have made myself as the 13th contributor), how do I push into your updated repo?

**Comment by ayan-b** [comment]
* First add this repo as an upstream: `git remote add upstream https://github.com/ayan-b/Linear-Search.git`
* Then update your repo: `git pull upstream master`
* Then make your changes and push to your repository.

**Comment by ayan-b** [comment]
Thanks for the PR, but as you can see the README.md here: https://github.com/ayan-b/Linear-Search/tree/a120c3094f2904375b06e1ab44875e312d86d4cc, it is not rendered properly. Simply remove the unnecessary lines and another commit. :smiley:

**Comment by vinayak42** [comment]
I made two commits, the other one removing the whacky stuff

**Comment by vinayak42** [comment]
Thanks for the help. Looking forward to more "genuine" contributions.

**Comment by ayan-b** [comment]
Ha Ha, XD. Tip: Join an Open Source org, people are really helpful out there. If you are into python, consider joining coala.

**Pull request merged**
